name: Release Staging
on:
  push:
    branches:
      - main
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  issues: write
  pull-requests: write
  actions: read
  packages: read
  id-token: write

jobs:
  release:
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Git User
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn prod

      - name: release
        env:
          GITHUB_TOKEN: ${{ secrets.githubToken }}
          NPM_TOKEN: ${{ secrets.githubToken }}
        run: pnpm exec semantic-release
